/*
  # Create Media Assets and Projects System

  ## Overview
  This migration creates a complete media production system for MandaStrong Studio, enabling users to:
  - Store and manage media assets (video, audio, images)
  - Create and organize projects with timelines
  - Track AI-generated content
  - Manage render jobs and exports

  ## New Tables

  ### 1. `projects`
  - `id` (uuid, primary key) - Unique project identifier
  - `user_id` (uuid, foreign key) - Project owner
  - `name` (text) - Project name
  - `description` (text) - Project description
  - `timeline_data` (jsonb) - Complete timeline state with video/audio/text tracks
  - `duration` (integer) - Total project duration in seconds
  - `created_at` (timestamptz) - Creation timestamp
  - `updated_at` (timestamptz) - Last modification timestamp

  ### 2. `media_assets`
  - `id` (uuid, primary key) - Unique asset identifier
  - `user_id` (uuid, foreign key) - Asset owner
  - `project_id` (uuid, foreign key, nullable) - Associated project
  - `name` (text) - Asset name
  - `type` (text) - Asset type: 'video', 'audio', 'image', 'text'
  - `file_path` (text) - Storage path in Supabase Storage
  - `file_size` (bigint) - File size in bytes
  - `duration` (integer, nullable) - Duration in seconds for video/audio
  - `width` (integer, nullable) - Width for video/image
  - `height` (integer, nullable) - Height for video/image
  - `ai_generated` (boolean) - Whether generated by AI tool
  - `ai_tool_name` (text, nullable) - Name of AI tool used
  - `ai_prompt` (text, nullable) - Generation prompt
  - `metadata` (jsonb) - Additional metadata
  - `created_at` (timestamptz) - Upload/creation timestamp

  ### 3. `render_jobs`
  - `id` (uuid, primary key) - Unique job identifier
  - `user_id` (uuid, foreign key) - Job owner
  - `project_id` (uuid, foreign key) - Source project
  - `status` (text) - Job status: 'pending', 'processing', 'completed', 'failed'
  - `quality` (text) - Export quality: 'hd', '4k', '8k'
  - `format` (text) - Export format: 'mp4', 'mov', 'webm'
  - `output_path` (text, nullable) - Final rendered file path
  - `progress` (integer) - Completion percentage (0-100)
  - `error_message` (text, nullable) - Error details if failed
  - `started_at` (timestamptz, nullable) - Processing start time
  - `completed_at` (timestamptz, nullable) - Completion time
  - `created_at` (timestamptz) - Job creation time

  ## Security
  - Enable RLS on all tables
  - Users can only access their own projects, assets, and render jobs
  - Authenticated users required for all operations

  ## Performance
  - Indexes on user_id columns for fast lookups
  - Indexes on project_id for asset queries
  - Index on render job status for queue management
*/

-- Create projects table
CREATE TABLE IF NOT EXISTS projects (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT 'Untitled Project',
  description text DEFAULT '',
  timeline_data jsonb DEFAULT '{"video":[],"audio":[],"text":[]}'::jsonb,
  duration integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create media_assets table
CREATE TABLE IF NOT EXISTS media_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE SET NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type IN ('video', 'audio', 'image', 'text')),
  file_path text NOT NULL,
  file_size bigint DEFAULT 0,
  duration integer,
  width integer,
  height integer,
  ai_generated boolean DEFAULT false,
  ai_tool_name text,
  ai_prompt text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- Create render_jobs table
CREATE TABLE IF NOT EXISTS render_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  quality text NOT NULL DEFAULT 'hd' CHECK (quality IN ('hd', '4k', '8k')),
  format text NOT NULL DEFAULT 'mp4' CHECK (format IN ('mp4', 'mov', 'webm')),
  output_path text,
  progress integer DEFAULT 0,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE render_jobs ENABLE ROW LEVEL SECURITY;

-- Projects policies
CREATE POLICY "Users can view own projects"
  ON projects FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own projects"
  ON projects FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own projects"
  ON projects FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own projects"
  ON projects FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Media assets policies
CREATE POLICY "Users can view own media assets"
  ON media_assets FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own media assets"
  ON media_assets FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own media assets"
  ON media_assets FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own media assets"
  ON media_assets FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Render jobs policies
CREATE POLICY "Users can view own render jobs"
  ON render_jobs FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own render jobs"
  ON render_jobs FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own render jobs"
  ON render_jobs FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own render jobs"
  ON render_jobs FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_updated_at ON projects(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_media_assets_user_id ON media_assets(user_id);
CREATE INDEX IF NOT EXISTS idx_media_assets_project_id ON media_assets(project_id);
CREATE INDEX IF NOT EXISTS idx_media_assets_type ON media_assets(type);
CREATE INDEX IF NOT EXISTS idx_render_jobs_user_id ON render_jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_render_jobs_project_id ON render_jobs(project_id);
CREATE INDEX IF NOT EXISTS idx_render_jobs_status ON render_jobs(status);

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for projects
DROP TRIGGER IF EXISTS update_projects_updated_at ON projects;
CREATE TRIGGER update_projects_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();